name: master

on:
  push:
    branches:
      - 'master'

jobs:
  build-new-tag:
    name: Create and publish new tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          INITIAL_VERSION: 0.0.0

      - name: Show tag
        run: echo ${{ steps.tag.outputs.new_tag }}
